title: Data Science with Python
author: Ashray Shetty
copyright: "2021"
logo: mvlogo.png

execute:
  execute_notebooks: 'off'

parse:
  myst_extended_syntax: true
  myst_enable_extensions:
    # https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # https://github.com/executablebooks/jupyter-book/blob/c923bdbfb178d3da478394d6149a7754034ed6fb/docs/_config.yml
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme: quantecon_book_theme
  extra_extensions: 
    - sphinx_multitoc_numbering
    - sphinx_inline_tabs
    - sphinx-prompt

launch_buttons:
  notebook_interface: "classic"  # or "jupyterlab"
  thebe                  : true


html_theme_options:
  header_organisation_url: https://www.multiverse.io/en-GB
  header_organisation: Multiverse
  repository_url: https://github.com/Ashray-shetty/bookcopy
  repository_branch: main
  path_to_docs: /Chapters
  nb_repository_url: https://github.com/Ashray-shetty/bookcopy
  og_logo_url: https://raw.githubusercontent.com/Ashray-shetty/bookcopy/main/Multiverse_Logo_RGB_Indigo-02.png
  launch_buttons: {
    binderhub_url: https://mybinder.org
    notebook_interface: classic
    thebe: true
    }


html:
  favicon: mvlogo.png
  navbar_footer_text: Visit our <a href="https://github.com/MultiverseDF/book">repository</a>

  use_repository_button: false       
  use_issues_button: false
  comments:
    utterances:
      repo: "github-org/github-repo"          
    hypothesis: true

repository:
  url: https://github.com/Ashray-shetty/bookcopy                   
  path_to_book: .                  
  branch: main

