title: Data Science with Python
author: Ashray Shetty
copyright: "2021"
logo: DC-2.png

only_build_toc_files: true
execute:
  execute_notebooks: "cache"
  timeout: 600

parse:
  myst_extended_syntax: true
  myst_enable_extensions:
    # https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # https://github.com/executablebooks/jupyter-book/blob/c923bdbfb178d3da478394d6149a7754034ed6fb/docs/_config.yml
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

sphinx:
  extra_extensions: [sphinx_multitoc_numbering, sphinxext.rediraffe, sphinx_tojupyter]
  config:
    nb_render_priority:
      html:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "text/latex"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/plain"
      jupyter:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "text/latex"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/plain"
    
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme: quantecon_book_theme


quantecon_book_theme:
    html_static_path: ['_static']
    html_theme_options:
      header_organisation_url: https://multiverse.io
      header_organisation: Multiverse
      repository_url: https://github.com/Ashray-shetty/bookcopy
      nb_repository_url: https://github.com/Ashray-shetty/bookcopy
      og_logo_url: https://assets.quantecon.org/img/qe-og-logo.png
      description: This website presents a set of lectures on Data fellowship
    mathjax_config:
      TeX:
        Macros:
          "argmax" : "arg\\,max"
          "argmin" : "arg\\,min"
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js
    rediraffe_redirects:
      index_toc.md: intro.md
    tojupyter_static_file_path: ["source/_static", "_static"]
    tojupyter_target_html: true
    tojupyter_urlpath: "https://ashray-shetty.github.io/bookcopy/"
    tojupyter_lang_synonyms: ["ipython", "ipython3", "python"]
    tojupyter_kernels:
      python3:
        kernelspec:
          display_name: "Python"
          language: python3
          name: python3
        file_extension: ".py"
    tojupyter_images_markdown: true

launch_buttons:
  notebook_interface: "classic"  # or "jupyterlab"
  thebe                  : true

html:
  favicon: DC-2.png
  navbar_footer_text: Visit our <a href="https://github.com/MultiverseDF/book">repository</a>

  use_repository_button: false       
  use_issues_button: false
  comments:
    utterances:
      repo: "github-org/github-repo"          
    hypothesis: true

repository:
  url: https://github.com/Ashray-shetty/bookcopy                    
  path_to_book: .                  
  branch: main

